config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get 'main'
    end
  end
  resources :messages

  mount ActionCable.server => '/cable'
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  protect_from_forgery except: :index
  def index
    @messages = Message.all
    @message = Message.new
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @message = User.last.messages.create!(message_params)
    @messages = Message.all
    ActionCable.server.broadcast 'room_channel',
                                 content: @message, user: @message.user
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def message_params
    params.permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create!(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="modal-holder"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/modal.html.erb
<!-- Modal -->
<div class="modal fade" id="approvalModal" tabindex="-1" role="dialog" aria-labelledby="approvalModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Approval</h4>
      </div>
      <div class="modal-body">
        <%= form_tag approve_leave_request_path(r), method: :get, :class => "form-horizontal" do %>
          <%= label_tag 'reason', 'Reason for Approval', :class => 'control-label' %>
          <%= text_field_tag :reason, params[:reason], :class => "form-control" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <%= submit_tag "Submit Approval", name: nil, class: "btn btn-success" %>
        <% end %>
        </div>
        </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/messages/_index.html.erb
<h1>Messages:</h1>
<div id="msg">
  <%= render partial: "messages/message", collection: @messages %>
</div>
<%=form_with url: messages_path, remote: true do |form| %>
  <p>
    <%=form.text_area :content%>
  </p>

  <p>
    <%= form.submit class: "btn btn-primary"%>
  </p>
<% end %>

app/views/messages/_message.html.erb
<h3><%= message.user.name %></h3>
<h5><%= message.content %></h5>

app/views/messages/create.js.erb
console.log("Create message");

app/views/messages/index.html.erb
<h1>Messages:</h1>
<div id="msg">
  <%= render partial: "messages/message", collection: @messages %>
</div>
<%=form_with url: messages_path, remote: true do |form| %>
  <p>
    <%=form.text_area :content%>
  </p>

  <p>
    <%= form.submit class: "btn btn-primary"%>
  </p>
<% end %>